version: 2.1

jobs:
  build:
    docker:
      # - image: naoyer/sample-git:latest
      - image: cimg/base:current
    resource_class: medium
    steps:
      - run: git --version
      - run: ssh -V
      - checkout

workflows:
  main:
    jobs:
      - build
